"""
Django settings for oauth_app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qmve2q)nhk94#iltjswj%1kb=idltc#3hzc82yux(3jru%+k_&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'django-oauth-erik.toolforge.org',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'social_django',
    'user_profile',
    'wiki_replica',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'oauth_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'oauth_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use MariaDB in production (Toolforge), SQLite locally
if os.environ.get('TOOLFORGE_DEPLOYMENT'):
    # Toolforge database configuration
    # Using environment variables that are automatically set by Toolforge:
    # - TOOL_TOOLSDB_USER: Username for tools database
    # - TOOL_TOOLSDB_PASSWORD: Password for tools database
    # Alternatively, read from ~/replica.my.cnf using read_default_file

    db_name = os.environ.get('TOOLSDB_NAME', 's57230__django_oauth_erik')
    wiki_code = os.environ.get('WIKI_REPLICA', 'metawiki')  # e.g., 'metawiki', 'enwiki', 'commonswiki'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,  # Private database (no _p suffix)
            'HOST': 'tools.db.svc.wikimedia.cloud',
            'PORT': '3306',
            'OPTIONS': {
                # Read credentials from ~/replica.my.cnf
                'read_default_file': os.path.expanduser('~/replica.my.cnf'),
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        },
        'wiki_replica': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': f'{wiki_code}_p',  # Wiki replica databases have _p suffix
            'HOST': f'{wiki_code}.analytics.db.svc.wikimedia.cloud',
            'PORT': '3306',
            'OPTIONS': {
                # Read credentials from ~/replica.my.cnf
                'read_default_file': os.path.expanduser('~/replica.my.cnf'),
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Local development with SQLite
    # Note: Wiki replica functionality won't work locally without SSH tunnel
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'wiki_replica': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'wiki_replica.sqlite3',
        }
    }

# Database routers
DATABASE_ROUTERS = ['wiki_replica.router.WikiReplicaRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fi', 'Finnish'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends
AUTHENTICATION_BACKENDS = (
    'social_core.backends.mediawiki.MediaWiki',
    'django.contrib.auth.backends.ModelBackend',
)

# Required workaround for T353593
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ['groups']

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'

# MediaWiki OAuth settings
SOCIAL_AUTH_MEDIAWIKI_KEY = os.environ.get('MEDIAWIKI_CONSUMER_KEY', '')
SOCIAL_AUTH_MEDIAWIKI_SECRET = os.environ.get('MEDIAWIKI_CONSUMER_SECRET', '')
SOCIAL_AUTH_MEDIAWIKI_URL = 'https://meta.wikimedia.org/w/index.php'
SOCIAL_AUTH_MEDIAWIKI_CALLBACK = os.environ.get('MEDIAWIKI_CALLBACK', 'http://127.0.0.1:8080/oauth/complete/mediawiki/')

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8080',
    'http://localhost:8080',
    'https://django-oauth-erik.toolforge.org',
]

CORS_ALLOW_CREDENTIALS = True
